// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrZiXYOaUWQjv3roqdD36Q-AvRwNfw84',
    appId: '1:696253376957:web:235cb92f52c4c0f649cad4',
    messagingSenderId: '696253376957',
    projectId: 'multi-rest-app',
    authDomain: 'multi-rest-app.firebaseapp.com',
    storageBucket: 'multi-rest-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPrUxsX_t3lSA4XPbJUjiFdgmWaeibu8E',
    appId: '1:696253376957:android:bc98b2619307ebca49cad4',
    messagingSenderId: '696253376957',
    projectId: 'multi-rest-app',
    storageBucket: 'multi-rest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3QWTdEgl9i9xsFArO6upe4TpQ2x2flk',
    appId: '1:696253376957:ios:29c4866df93de75549cad4',
    messagingSenderId: '696253376957',
    projectId: 'multi-rest-app',
    storageBucket: 'multi-rest-app.firebasestorage.app',
    iosBundleId: 'com.multiVendors.app',
  );

}